### ISSUE TITLE
JID not working

### ISSUE THREAD

**Issue by karolstaniek** [xmppo/Jabber-Net#92] opened 2017-11-13 14:20 UTC
Hi,
I keep getting error on JID:
Did not provide required parameter: \r\nParameter name: jid
I used example code with only parameters changed for connection.

Any ideas what can cause this error?

**Comment by ForNeVeR** [comment] 2017-11-13 14:21
Hello. Could you please clarify, what exact steps are you taking to get that error?

**Comment by karolstaniek** [comment] 2017-11-13 14:25
I basically just changed connection parameters:
```C#
JabberClient jc = new JabberClient(); 
            jc.OnReadText += new bedrock.TextHandler(jc_OnReadText); 
            jc.OnWriteText += new bedrock.TextHandler(jc_OnWriteText); 
            jc.OnError +=new bedrock.ExceptionHandler(jc_OnError); 
            jc.OnStreamError += new jabber.protocol.ProtocolHandler(jc_OnStreamError);

            //JID j = new JID(jid);
            jc.User = "myUser";
            jc.Server = "myServer";
            jc.NetworkHost = "myHost";
            jc.Port = 5222;
            jc.Resource = "Jabber.Net Console Client";
            jc.Password = "myPassword";

            jc.AutoReconnect = 3f; 


            GetOpt go = new GetOpt(this); 
            try 
            { 
                go.Process(args); 
            } 
            catch (ArgumentException e) 
            { 
                go.UsageExit(); 
            } 
```

I'm using Cisco Jabber.

Many thanks in advance

**Comment by ForNeVeR** [comment] 2017-11-13 14:30
Are you running the code from the console example? If so, then what command line arguments are you providing?

It looks like you actually haven't passed the `jid` command line argument, and it's required in the console example.

Probably you just need to remove `go.Process(args)` part, if you don't want to process the command line arguments at all.

**Comment by karolstaniek** [comment] 2017-11-13 14:44
![alt text](https://s17.postimg.org/v9fao2vun/code_snip.png "Preview")

For some reason none of the arguments are passed, when provided at following schema:
```C#

        [CommandLine("j", "myUser@myServer", true)] 
        public string jid = null; 


        [CommandLine("p", "myPassword", false)] 
        public string pass = null; 


        [CommandLine("n", "myHost", false)] 
        public string networkHost = null; 


        [CommandLine("o", "Port", false)] 
        public int port = 5222; 
```

**Comment by ForNeVeR** [comment] 2017-11-13 14:44
How are you passing them?

**Comment by karolstaniek** [comment] 2017-11-13 14:50
```C#
        static void Main(string[] args) 
         {
             try
             {
                 new Program(args);
             }
             catch (Exception ex)
             {

             }
             //Thread.Sleep(15000);
         } 
```

**Comment by ForNeVeR** [comment] 2017-11-13 14:53
I think you have problem understanding the `GetOpt` class. It takes the arguments from the command line and places them into the fields `jid`, `pass` so on.

Some of the command line arguments are explicitly marked as `required = true` in the example program (e.g. `jid`). From your screenshot, it looks like you're passing no arguments to the program. That's the reason `GetOpt` throws an exception.

It also looks like you think the second argument of `CommandLine` could define a default value for the argument. It's wrong; the second argument is `description`; [take a look at the source](https://github.com/ForNeVeR/Jabber-Net/blob/1933189ff8331379f77357193dad9d8a246af5a0/src/JabberNet/bedrock/util/GetOptBase.cs#L507).

To solve your problem, please pass the command line arguments to the program. E.g.

```console
JabberNet.ConsoleClient.exe -j user2@example.com -p password
```

**Comment by ForNeVeR** [comment] 2017-12-10 03:51
Closing due to a missing response from the original poster. Feel free to discuss and reopen if the issue is still unsolved.

**Closed as completed by ForNeVeR** 2017-12-10 03:51 UTC
Labels: kind:bug, status:discussion
