### ISSUE TITLE
NuGet package has incorrect reference to netlib.Dns

### ISSUE THREAD

**Issue by pergardebrink** [xmppo/Jabber-Net#103] opened 2019-08-31 17:20 UTC
I had some warnings in Visual Studio about it having conflicts about netlib.Dns when adding the jabber-net package. 

I looked into the files inside thhe nuget package and it seems as for version 2.1.2, jabber-net.dll is referencing netlib.Dns, Version=1.1.5859.29905, Culture=neutral, PublicKeyToken=924c5b18328d6f09. But the provided netlib.Dns.dll in the NuGet package is of version netlib.Dns, Version=1.1.5859.29820, Culture=neutral, PublicKeyToken=924c5b18328d6f09

Maybe not the biggest issue since it seems to be able to resolve it correctly anyways.

**Comment by ForNeVeR** [comment] 2019-09-15 10:35
Yeah, you're right, thanks for noticing.

For now, I definitely don't want to invest more time into 2.x version, and the issue is already fixed in the preview packages for 3.0.

**Closed as completed by ForNeVeR** 2019-09-15 10:35 UTC
Labels: kind:bug

**Comment by pergardebrink** [comment] 2019-09-15 10:50
Yes, that makes perfect sense ofc! 

Btw, are there any plans for merging the netstandard pull request I saw you had also? At some point later I would like to target NET Core, but that could take a while. Is there anything I could do to help out?

**Comment by ForNeVeR** [comment] 2019-09-15 11:03
In previous years I was (as pretty much everyone else) very confused about .NET Core & .NET Standard thing, that's why you could possibly find traces of all the things in this repo: .NET Core migration plans, .NET Standard migration plans, maybe even a `project.json` or two. Now I (as pretty much everyone else?) have the stuff sorted out in my mind, and may proceed with performing the port.

(It should also be much easier with a modern .NET Standard — like, 2.0, and not that ol' good 1.3)

Honestly, I had prioritized tasks such as #95 more (because deadlock seems like a serious issue), but it's not very easy to fix, and may take me another year or two… 😿

But if you're interested in having a .NET Standard port of this library, I guess I may raise the priority on it. It looks like PR #84 should have only some minor compilation issues. If possible, could you please take a look at them? I am pretty busy these days, and don't think I'd be able to take a look at this PR this month.
